### ISSUE TITLE
demo with transformations not working

### ISSUE THREAD

**Issue by mbilalshaikh** [RaivoKoot/Video-Dataset-Loading-Pytorch#11]
AttributeError: 'list' object has no attribute 'size'

**Comment by mbilalshaikh** [comment]
ansforms/transforms.py", line 175, in __call__
    return F.normalize(tensor, self.mean, self.std, self.inplace)
  File "/home/muhammadbsheikh/anaconda3/envs/open-mmlab2/lib/python3.7/site-packages/torchvision/transforms/functional.py", line 210, in normalize
    raise TypeError('tensor is not a torch image.')
TypeError: tensor is not a torch image.

**Comment by RaivoKoot** [comment]
If I clone and run
```
python demo.py
```

everything works. Can you give me more information on your issue please, so that I can help you. You need to tell me which line in `demo.py` the error originates from.
