### ISSUE TITLE
END_FRAME

### ISSUE THREAD

**Issue by sherrijj** [RaivoKoot/Video-Dataset-Loading-Pytorch#17]
Thanks for your code, it's great. I wonder to create the annotation file if the END_FRAME of the video must be known in advance?

**Comment by RaivoKoot** [comment]
Thanks! In general, yes. 
The  typical workflow would go:
1) Download dataset of videos
2) For each video, create a folder and put each frame as a jpg file into it
3) Count how many jpg files are in each video's folder, and create the annotation file.

This would be the common approach. If there is some use case where you don't know the number of frames per video in advance, then you might have to make some modifications to the dataloading code (the code is relatively simple).

**Comment by RaivoKoot** [comment]
Feel free to share your use case here. I am curious.

**Comment by sherrijj** [comment]
sure.
