### ISSUE TITLE
Extra whitespace characters in the annotation file breaks

### ISSUE THREAD

**Issue by pifry** [RaivoKoot/Video-Dataset-Loading-Pytorch#6]
The program breaks, when there are extra whitespace characters in the annotation file e.g.

```
bs 2        5       1
bs 6        8       2
bs 9        12      3
bs 13       16      4
```

The extra white space chars makes the annotation file more readable and editable with [column selection mode](https://code.visualstudio.com/docs/editor/codebasics#_column-box-selection). Therefore, I think, it will be nice to be ready for such an extra whitespace. 
If You think it's an issue, I can handle it.

**Comment by RaivoKoot** [comment]
Hmm indeed. Thanks for bringing this up! I think this is a bug. I think i can easily fix it without much effort. So, no worries from your side. Ill update this thread when im done later!

**Comment by RaivoKoot** [comment]
#7 
This should fix it now. Works on my end. Can you let me know whether this fixes it for you too?

**Comment by pifry** [comment]
Issue fixed.
